export const dummmy = {
  dates: { maximum: "2024-10-23", minimum: "2024-09-11" },
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: "/v9acaWVVFdZT5yAU7J2QjwfhXyD.jpg",
      genre_ids: [16, 878, 10751],
      id: 1184918,
      original_language: "en",
      original_title: "The Wild Robot",
      overview:
        "우연한 사고로 거대한 야생에 불시착한 로봇 로즈는 주변 동물들의 행동을 배우며 낯선 환경 속에 적응해 가던 중, 사고로 세상에 홀로 남겨진 아기 기러기 브라이트빌의 보호자가 된다. 로즈는 입력되어 있지 않은 새로운 역할과 관계에 낯선 감정을 마주하고 겨울이 오기 전에 남쪽으로 떠나야 하는 브라이트빌을 위해 동물들의 도움을 받아 이주를 위한 생존 기술을 가르쳐준다. 그러나 선천적으로 몸집이 작은 브라이트빌은 짧은 비행도 힘겨워 하는데...",
      popularity: 2282.501,
      poster_path: "/8dkuf9IuVh0VZjDTk7kAY67lU0U.jpg",
      release_date: "2024-10-01",
      title: "와일드 로봇",
      video: false,
      vote_average: 8.538,
      vote_count: 372,
    },
    {
      adult: false,
      backdrop_path: "/zAqBIeO71BFL7bAtP5TFzVjVamy.jpg",
      genre_ids: [10749, 18],
      id: 1079091,
      original_language: "en",
      original_title: "It Ends with Us",
      overview:
        "아버지의 장례식을 멋지게 망치고 아지트로 향한 ‘릴리’는 어딘가 위태롭지만 매력적인 남자 ‘라일’에게 순식간에 마음을 빼앗긴다. 새로운 도시에서 자신의 이름을 건 꽃집을 오픈한 릴리는 운명처럼 라일을 다시 만나게 되고 걷잡을 수 없는 사랑에 빠져든다. 그러던 어느 날, 어린 시절의 모든 상처를 알고 있는 첫사랑 ‘아틀라스’와 우연히 재회한 후 감당하기 벅찬 라일의 위협적인 모습을 목격하게 되고 완벽했던 관계가 순식간에 요동치면서 릴리는 피할 수 없는 선택의 기로에 서게 되는데… 외면하고 싶지만 마주해야 하는 사랑과 선택의 순간 올가을, 모두에게 위로와 용기를 선사하는 특별한 이야기!",
      popularity: 670.41,
      poster_path: "/287MYoxjfINSyfaaV636Z2ioR36.jpg",
      release_date: "2024-09-13",
      title: "우리가 끝이야",
      video: false,
      vote_average: 7.1,
      vote_count: 799,
    },
    {
      adult: false,
      backdrop_path: "/reNf6GBzOe48l9WEnFOxXgW56Vg.jpg",
      genre_ids: [18, 80, 53],
      id: 889737,
      original_language: "en",
      original_title: "Joker: Folie à Deux",
      overview:
        "2년 전, 세상을 뒤흔들며 고담시 아이콘으로 자리한 아서 플렉은 아캄 수용소에 갇혀 최종 재판을 앞둔 무기력한 삶을 살아간다. 그러던 어느 날, 수용소에서 운명적으로 만난 리 퀸젤은 아서의 삶을 다시 뒤바꾸며 그의 마음 속에 잠들어 있던 조커를 깨우고 리 역시 각성하며 자신을 할리 퀸이라 지칭하며 서로에게 깊이 빠져든다. 무고한 시민을 죽인 죄로 재판에 오르게 된 아서. 그는 최후의 심판대에서 할리 퀸과 함께 자신, 조커의 이야기를 시작하는데…",
      popularity: 594.92,
      poster_path: "/dA1TGJPTVjlqPc8PiEE2PfvFBUp.jpg",
      release_date: "2024-10-01",
      title: "조커: 폴리 아 되",
      video: false,
      vote_average: 5.8,
      vote_count: 780,
    },
    {
      adult: false,
      backdrop_path: "/1fL2S8LKxCVE9KoPRBXeagmBtex.jpg",
      genre_ids: [27, 53],
      id: 1114513,
      original_language: "en",
      original_title: "Speak No Evil",
      overview:
        "휴양지에서 처음 만나 우연히 함께 휴가를 보내게 된 두 가족. 패트릭(제임스 맥어보이)은 자신의 집으로 루이스(맥켄지 데이비스)의 가족을 초대한다. 다시 만나 즐거운 시간을 보낼 것이라 예상한 것도 잠시, 거절할 수 없는 호의와 불편한 상황들이 계속되며 불길한 두려움을 느끼고 집에 돌아가려 하던 중 숨겨진 진실을 마주하게 되는데…",
      popularity: 725.081,
      poster_path: "/mXGlp8K10JhiY5ZNY7zMldm2lss.jpg",
      release_date: "2024-09-11",
      title: "스픽 노 이블",
      video: false,
      vote_average: 7.352,
      vote_count: 660,
    },
    {
      adult: false,
      backdrop_path: "/3sh2UA2Q2l7fihgoj1LhFFPTlIM.jpg",
      genre_ids: [28, 878, 12],
      id: 912649,
      original_language: "en",
      original_title: "Venom: The Last Dance",
      overview:
        "환상의 케미스트리의 에디 브록과 그의 심비오트 베놈은 그들을 노리는 정체불명 존재의 추격을 피해 같이 도망을 다니게 된다. 한편 베놈의 창조자 널은 고향 행성에서부터 그들을 찾아내기 위해 지구를 침략하고 에디와 베놈은 그동안 겪어보지 못한 최악의 위기를 맞이하게 되는데…",
      popularity: 506.354,
      poster_path: "/3flIDcZF3tnR7m5OU2h7lLPQwmr.jpg",
      release_date: "2024-10-23",
      title: "베놈: 라스트 댄스",
      video: false,
      vote_average: 0.0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: "/m1DkRQbNXjs2RYC0FP4r6mdaLCi.jpg",
      genre_ids: [16, 878, 12, 10751, 28],
      id: 698687,
      original_language: "en",
      original_title: "Transformers One",
      overview:
        "사이버트론 행성의 지하 광산에서 일하는 변신 못 하는 하급 로봇 오라이온 팩스와 D-16. 한 번도 가보지 못한 지상 세계를 꿈꾸던 둘은 쾌활한 수다쟁이 B-127, 카리스마 넘치는 엘리타 원과 함께 출입이 금지된 지상에 도달한다. 지상에서 잠들어 있던 알파 트라이온을 만난 넷은 그의 도움으로 잠재되어 있던 변신 능력을 얻게 된다. 막강한 힘과 변신 능력으로 자유를 느낀 것도 잠시, 자신들의 행성을 지배하고 있는 거대한 배후의 존재를 알게 되며 모든 것을 바꿀 전쟁을 시작하는데…",
      popularity: 383.713,
      poster_path: "/c2JXlWzvXegSda8qaATr8I47kMx.jpg",
      release_date: "2024-09-25",
      title: "트랜스포머 ONE",
      video: false,
      vote_average: 7.5,
      vote_count: 146,
    },
    {
      adult: false,
      backdrop_path: "/AjTodtZJlQxycfRPktnUTpknblv.jpg",
      genre_ids: [16, 12, 35, 10751],
      id: 1207830,
      original_language: "en",
      original_title: "Gracie \u0026 Pedro: Pets to the Rescue",
      overview:
        "자신이 최고라고 생각하는 품격 있는 강아지 ‘그레이시’와 장난기 많은 스트릿 출신 고양이 ‘페드로’가 공항 수화물 사고로 가족과 떨어지게 된다. 상상 이상의 위험이 기다리고 있는 와일드한 바깥세상에 던져진 그레이시와 페드로, 과연 무사히 집으로 돌아갈 수 있을까? 못 말리는 사고뭉치 콤비, 사랑하는 가족을 만나기 위해 우리가 뭉쳐야만 한다! 멍X냥 크로스!",
      popularity: 262.58,
      poster_path: "/k38P9SbCmUTwW0BHUl7qGbAbEli.jpg",
      release_date: "2024-10-23",
      title: "마이펫의 컴백홈 어드벤처",
      video: false,
      vote_average: 6.813,
      vote_count: 16,
    },
    {
      adult: false,
      backdrop_path: "/cVg97LOJgrDZJ7bVmjU2KsGRYnU.jpg",
      genre_ids: [27, 9648],
      id: 1100782,
      original_language: "en",
      original_title: "Smile 2",
      overview:
        "월드투어를 앞두고 자신의 눈 앞에서 기괴한 미소와 함께 끔찍한 죽음을 맞은 친구를 목격한 팝스타 ‘스카이’. 그 날 이후 공연 리허설과 팬 미팅 행사 등 그녀의 삶 곳곳에서 끔찍한 일들이 잇따라 발생한다. 화려한 스타의 삶을 뒤덮은 공포에서 벗어나기 위해 몸부림치던 ‘스카이’는 자신이 죽어야만 전염처럼 번지는 저주가 끝난다는 사실을 듣게 되는데…",
      popularity: 279.202,
      poster_path: "/4nQk1OgbtdnKYMEQiOwwMB4yGxn.jpg",
      release_date: "2024-10-16",
      title: "스마일 2",
      video: false,
      vote_average: 7.0,
      vote_count: 3,
    },
    {
      adult: false,
      backdrop_path: "/9juRmk8QjcsUcbrevVu5t8VZy5G.jpg",
      genre_ids: [28, 12, 80, 53],
      id: 923667,
      original_language: "cn",
      original_title: "九龍城寨之圍城",
      overview:
        "1980년대 홍콩 내 위험하고 불가사의했던 무법지대, 구룡성채! 악명 높은 갱단에게서 도망치려던 '진락군'은 우연히 구룡성채로 도망가게 되고,  성채의 일원들의 도움을 받아 목숨을 건진다. 그 후 '진락군'은 성채의 일원이 되어 생애 첫 보금자리를 가지게 되는데...  행복도 잠시, 오랫동안 성채를 노린 악당들이 들이닥치고 그들은 최후의 전쟁을 시작하게 된다.",
      popularity: 218.932,
      poster_path: "/aUXq8aK2UX1CoQbxUi4fyioPOgH.jpg",
      release_date: "2024-10-16",
      title: "구룡성채: 무법지대",
      video: false,
      vote_average: 6.5,
      vote_count: 187,
    },
    {
      adult: false,
      backdrop_path: "/9utq8PrMyvFBtlte2BDNaj1ktSi.jpg",
      genre_ids: [12, 10751],
      id: 1088563,
      original_language: "de",
      original_title: "Lassie - Ein neues Abenteuer",
      overview:
        "휴가를 맞아 ‘래시’와 함께 이모네에 놀러 간 ‘플로’는 이모가 입양한 ‘헨리’와 ‘클레오’ 남매를 만난다.  함께 아이스크림을 먹으러 나간 시내에서 강아지들을 스토킹하는 수상한 커플을 만나게 되고, 집에 ‘플로’만 있던 날에 강아지 ‘피파’를 도둑맞는다.  잃어버린 ‘피파‘를 찾기 위해 ‘래시’는 집을 떠나고, ‘플로‘와 ‘클레오’는 ‘래시’를 따라나서는데…",
      popularity: 190.574,
      poster_path: "/6I3eoCepAKeqwwjfP6VXeVAyUa8.jpg",
      release_date: "2024-09-12",
      title: "래시: 뉴 어드벤처",
      video: false,
      vote_average: 6.4,
      vote_count: 10,
    },
    {
      adult: false,
      backdrop_path: "/p5kpFS0P3lIwzwzHBOULQovNWyj.jpg",
      genre_ids: [53, 80],
      id: 1032823,
      original_language: "en",
      original_title: "Trap",
      overview:
        "10대 딸과 함께 인기 팝스타의 콘서트를 찾은 쿠퍼. 신나게 콘서트를 즐기던 그는 순간 이상한 낌새를 느끼고, 그곳이 최악의 연쇄살인마를 잡기 위한 거대한 덫임을 알게 된다. 그런데 문제는 쿠퍼 자신이 바로 연쇄살인마라는 것! 이제 쿠퍼는 수많은 관객과 경찰을 따돌리고 어린 딸과 함께 무사히 이 덫에서 탈출해야만 하는데…",
      popularity: 187.935,
      poster_path: "/2LC4gLNbHpZTq28EWOwCMiVnGcq.jpg",
      release_date: "2024-09-18",
      title: "트랩",
      video: false,
      vote_average: 6.517,
      vote_count: 1317,
    },
    {
      adult: false,
      backdrop_path: "/pmPDfocouP0mS1UjiRDSqUdNIWH.jpg",
      genre_ids: [18, 36],
      id: 1182047,
      original_language: "en",
      original_title: "The Apprentice",
      overview:
        "세입자들에게 밀린 집세를 받으러 다니는 뉴욕 부동산 업자의 아들 ‘도널드 트럼프’는 어느 날 정·재계 고위 인사들을 변호하며 정치 브로커로 활동하는 변호사 ‘로이 콘’을 만나게 된다. 성공을 향한 강한 야망을 가진 ‘도널드 트럼프’는 불법 수사와 협박, 사기, 선동으로 인간의 탈을 쓴 악마라고 불리는 ‘로이 콘’을 스승으로 삼고 더욱 악랄한 괴물로 거듭나는데!",
      popularity: 115.623,
      poster_path: "/36t19mk84eUaAysyWb29CHp3Rcv.jpg",
      release_date: "2024-10-23",
      title: "어프렌티스",
      video: false,
      vote_average: 7.0,
      vote_count: 16,
    },
    {
      adult: false,
      backdrop_path: "/eTvN54pd83TrSEOz6wbsXEJktCV.jpg",
      genre_ids: [10752, 28, 53],
      id: 882569,
      original_language: "en",
      original_title: "Guy Ritchie's The Covenant",
      overview:
        "끝이 보이지 않았던 전쟁의 한가운데 미 육군 소속 상사 ‘존 킨리’(제이크 질렌할)는 습격을 당한다. 목숨을 잃을 절체절명의 순간, 그는 현지 통역사 ‘아메드’(다 살림)의 도움으로 생환에 성공하고 ‘아메드’와 그의 가족들이 미국에서 살 수 있도록 최선을 다 하겠다고 약속한다  생환 이후의 어느 날, ‘존 킨리’는 자신을 도와주었던 ‘아메드’가 미국에 오지 못했으며 적들에게 억류되어 있다는 사실을 알게 된다.",
      popularity: 130.644,
      poster_path: "/11EHXs37YRZPyIyJjlUB2FAnbys.jpg",
      release_date: "2024-09-27",
      title: "더 커버넌트",
      video: false,
      vote_average: 7.761,
      vote_count: 2439,
    },
    {
      adult: false,
      backdrop_path: "/cavK9ox37pxDg11RvJINMH63onU.jpg",
      genre_ids: [27, 53],
      id: 744857,
      original_language: "es",
      original_title: "Cuando acecha la maldad",
      overview:
        "외딴 마을, 잔혹한 살인 사건의 실마리를 쫓던 형제는 마을 속에 숨어 지내는 한 가족이 관련된 것을 알게 된다. 악령이 깃들어 온몸이 부패해 죽어가는 아들 ‘유리엘’을 숨겨왔던 것. 두 형제는 ‘유리엘’을 마을 밖으로 유기하려 하지만 이미 악령의 봉인이 풀리고 마을을 잠식하는데...",
      popularity: 92.985,
      poster_path: "/yuPb1LbTnTm5WVivAhs4amUOgtV.jpg",
      release_date: "2024-10-09",
      title: "악이 도사리고 있을 때",
      video: false,
      vote_average: 7.4,
      vote_count: 943,
    },
    {
      adult: false,
      backdrop_path: "/mwdt9HsCddye6xzNvccPenaenjW.jpg",
      genre_ids: [16, 18, 35, 878],
      id: 838240,
      original_language: "es",
      original_title: "Robot Dreams",
      overview:
        "뉴욕 맨해튼에서 홀로 외롭게 살던 도그는 TV를 보다 홀린 듯 반려 로봇을 주문하고 그와 둘도 없는 단짝이 되어 행복한 나날을 보낸다. 그러던 어느 날, 해수욕장에 놀러간 도그와 로봇은 예기치 못한 상황에 휩쓸려 이별을 맞이하게 되는데···",
      popularity: 70.348,
      poster_path: "/3TfgJPOx7lzuopbXimsvYGq4vn6.jpg",
      release_date: "2024-03-13",
      title: "로봇 드림",
      video: false,
      vote_average: 8.071,
      vote_count: 512,
    },
    {
      adult: false,
      backdrop_path: "/kwGvFyRtGSSm8AFfnRNXoZTQmJj.jpg",
      genre_ids: [80, 18],
      id: 1008409,
      original_language: "en",
      original_title: "The Bikeriders",
      overview:
        "1960년대 미국이 격변하던 시절, ‘캐시’(조디 코머)는 우연히 바에서 만난 중서부 오토바이 클럽 반달스의 신입 멤버인 ‘베니’(오스틴 버틀러)에게 끌리게 된다. 이 클럽은 정체불명의 리더 ‘조니’(톰 하디)가 이끌고 있으며, 클럽이 진화해가며 각 지역 아웃사이더들이 모이는 장소의 위험한 폭력 범죄 조직으로 변해간다. 이로 인해 ‘베니’는 ‘캐시’와 클럽에 대한 충성심 사이, 선택의 기로에 놓이게 되는데...",
      popularity: 72.251,
      poster_path: "/n6RfhGJBBqeVrxOA67r65TECQXQ.jpg",
      release_date: "2024-09-25",
      title: "바이크 라이더스",
      video: false,
      vote_average: 6.856,
      vote_count: 589,
    },
    {
      adult: false,
      backdrop_path: "/jtSCugyOC4gtKqVXK3WaaxRNzqZ.jpg",
      genre_ids: [18],
      id: 1103621,
      original_language: "th",
      original_title: "หลานม่า",
      overview:
        "게임 폐인으로 살던 ‘엠’은 친가 사촌이 할아버지를 간병하고 집을 상속받자, 할머니의 유산을 받기 위해 할머니와 불편한 동거를 시작한다. 새벽 5시부터 죽 장사 돕기, 끝나지 않은 병원 대기 줄 서기를 하며 티격태격하던 할머니와 ‘엠’은 점점 가까워지는데…",
      popularity: 68.569,
      poster_path: "/wBsVETlndUADx0VN0VTtLn837PD.jpg",
      release_date: "2024-10-09",
      title: "할머니가 죽기 전 백만장자가 되는 법",
      video: false,
      vote_average: 7.8,
      vote_count: 52,
    },
    {
      adult: false,
      backdrop_path: "/fUHuBNqTFGCohCuHDEqHs1pDPj7.jpg",
      genre_ids: [12, 9648, 16],
      id: 21422,
      original_language: "ja",
      original_title: "名探偵コナン 時計じかけの摩天楼",
      overview:
        "검은 조직에 의해 초등학생 코난의 몸으로 작아진 고등학생 명탐정 쿠도 신이치. 천재 건축가 모리야 테이지 교수에게 가든 파티의 초대를 받았지만, 코난인 상태로는 참석할 수 없어 대리인을 부탁하려 소꿉친구 모리 란에게 목소리 변조기를 사용해 신이치로서 전화를 건다. 하지만 란이 신이치의 생일 전날인 5월 3일 밤 10시, 심야 영화를 보자고 조건을 걸어 난처해지고 만다. 약속 당일, 뉴스에서 화약 도난 사건을 보던 코난이자 신이치에게 수상한 협박 전화가 걸려 오고 의문의 남자가 도심 전체를 표적으로 한 연쇄 폭탄 테러를 예고한다. 자신에게 도전장을 내민 연쇄 폭탄 테러임을 알아챈 신이치는 범인과의 숨 막히는 대결 중, 베이카 시티 빌딩에 있는 란이 타깃이 되어 위험에 처했음을 깨닫는데…",
      popularity: 39.592,
      poster_path: "/ND2vNSrxd3BiiaxYDyqQ9IiZxO.jpg",
      release_date: "2024-10-02",
      title: "명탐정 코난: 시한장치의 마천루",
      video: false,
      vote_average: 7.4,
      vote_count: 225,
    },
    {
      adult: false,
      backdrop_path: "/6XQIukr8kNXr4NMNsFcekSi2Sds.jpg",
      genre_ids: [18, 10749],
      id: 884139,
      original_language: "ko",
      original_title:
        "우리는 천국에 100 18343  100 18343    0     0   427k      0 --:--:-- --:--:-- --:--:--  436k롯데리아 알바생 예지에게 친구 민호의 고백 쪽지를 대신 전해주고 집에 가던 길, 동료 태권도 부원들에게 집단 폭행을 당한다. 버거 사은품인 장난감 사이렌을 울리며 다가온 예지, 우연인지 필연인지 엄마의 청소년 사회화 프로그램으로 둘은 함께 살게 된다. 엄마의 제안으로 친구 성희, 민우, 그리고 예지와 익산으로 떠난 여행에서 주영은 처음 만난 순간부터 싹 튼 미묘한 감정을 확인한다. 꿈 같은 시간이 끝난 후, 다시 돌아온 현실은 서로를 좋아한다는 이유만으로 둘을 떼어놓으려 한다. 연민일 뿐이라는 어른들과 달리 주영과 예지는 사랑을 확신하며, 마지막까지 자신들의 선택에 대한 책임과 소중한 존재를 지켜내고자 하는데…",
      popularity: 47.327,
      poster_path: "/xPh9KN9eQ3Q8RFpXiXBF2eii3Pb.jpg",
      release_date: "2024-10-16",
      title: "우리는 천국에 갈 순 없지만 사랑은 할 수 있겠지",
      video: false,
      vote_average: 0.0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: "/6VoxDupaW2VXfLtJyeOoGCgXSjD.jpg",
      genre_ids: [28, 53],
      id: 1116490,
      original_language: "en",
      original_title: "Cash Out",
      overview:
        "전설적인 강도단의 보스 ‘메이슨’(존 트라볼타) 실패로 끝난 작전 이후 은퇴하고 잠적했던 그가 옛 팀원들의 다급한 요청으로 은행 강도 현장에 도착한다.  하지만 현장은 곧 치밀한 작전 따윈 사라지고 예상치 못한 FBI 협상가까지 등장하며 엉망이 되어버린다.  ‘메이슨’은 이제 FBI에 맞서 팀원들을 지키고 인생 마지막 한탕을 성공시키기 위해 완벽한 플랜 B를 설계하기 시작하는데…",
      popularity: 58.106,
      poster_path: "/4r77ZO9pKgQuW1GxjMrktyY8eUP.jpg",
      release_date: "2024-09-12",
      title: "캐시 아웃",
      video: false,
      vote_average: 5.9,
      vote_count: 65,
    },
  ],
  total_pages: 5,
  total_results: 85,
};
